usr/lib/kde4/activitymanager_uihandler_declarative.so
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/metadata.desktop
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/contents/ui/PasswordDialog.qml
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/contents/ui/uihandler.qml
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/contents/ui/NewPasswordDialog.qml
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/contents/ui/ChoiceDialog.qml
usr/share/kde4/apps/plasma/packages/org.kde.ActivityManager.UiHandler/contents/ui/MessageDialog.qml

